### ISSUE TITLE
 hardware

### ISSUE THREAD

**Issue by tjuxiaoli** [SensenGao/VLPTransferAttack#2]
Could you please let me know what kind of hardware is needed to run this code? Thank you

**Comment by SensenGao** [comment]
I recommend using a Linux platform. For the GPU, you'll likely need around **40GB** of VRAM. Alternatively, you can reduce the memory requirements to approximately **15GB** by limiting the **model_list** to only include CLIP_ViT and CLIP_CNN for validation.

**Comment by tjuxiaoli** [comment]
Got it, thank you for your response
