### ISSUE TITLE
Question of Adversarial Transferability on Large Language Models

### ISSUE THREAD

**Issue by returnaaa** [SensenGao/VLPTransferAttack#3]
Here, we further extend experiments by randomly selecting 100 images from the Flick30K and generating adversarial images using SGA and our method with ALBEF as the surrogate, under the same perturbation setting (16/255). Then, we feed adversarial images into LLMs and query "Describe this image", and rank descriptions with 100 irrelevant texts based on CLIP similarity.
I don't understand the comparison process of the above experiment. The adversarial samples generated by the two methods are input into the big model to obtain descriptions. 100 irrelevant samples are ranked according to CLIP similarity. If the description is ranked in the topN, the attack is considered successful. Where do the 100 irrelevant samples come from? With whom is the similarity calculated? And with whom is the similarity calculated for the description generated by the adversarial sample?

**Comment by SensenGao** [comment]
Hi, You can think of these 100 texts as being randomly selected from the Flickr dataset, but they must not include the texts corresponding to the images you have chosen. For example, you can select the first 100 images from the Flickr30K dataset, but you need to pick 100 texts associated with images other than these. For each selected image, if we generate a description using GPT for the clean image and mix it with these 100 texts, the description of the clean image will have the highest similarity to the clean image itself, ranking first. However, for an adversarial image, its generated description might not rank first. In this case, we consider the attack to be successful.

It is worth noting that the similarity ranking is performed between these 101 texts and the previous clean images. The perturbation used is set to 16/255, with 100 steps, and a single step size of 0.5/255.

**Comment by returnaaa** [comment]
thank you!!!
